#!/usr/bin/env bash
# Local deployment for plane-cli: install the binary and generate
# ~/.config/plane-cli/ (config.toml + per-instance key files) from existing
# KEY=value env files, so `plane` works standalone for any shell, agent,
# or systemd unit without sourcing anything.
#
# Usage: scripts/deploy.sh [--instance NAME=ENVFILE]... [--default NAME]
#                          [--prefix DIR] [--force]
#
#   --instance NAME=FILE  add instance NAME from env FILE (repeatable). FILE
#                         must define PLANE_API_KEY, PLANE_BASE_URL and
#                         PLANE_WORKSPACE_SLUG (or PLANE_WORKSPACE).
#                         Default when no --instance is given:
#                           work=~/.config/plane/proximal-mcp.env
#                           personal=~/.config/plane/harm-mcp.env (skipped
#                           with a warning if unreadable)
#   --default NAME        default_instance (default: first instance)
#   --prefix DIR          install prefix (binary goes to DIR/bin). Default ~/.local.
#   --force               overwrite a config.toml this script did not generate.
#
# API keys are written to ~/.config/plane-cli/key-NAME (0600), never printed.
set -euo pipefail

PREFIX="${HOME}/.local"
FORCE=0
DEFAULT_NAME=""
NAMES=()
FILES=()
while [ $# -gt 0 ]; do
  case "$1" in
    --instance) NAMES+=("${2%%=*}"); FILES+=("${2#*=}"); shift 2 ;;
    --default)  DEFAULT_NAME=$2; shift 2 ;;
    --prefix)   PREFIX=$2; shift 2 ;;
    --force)    FORCE=1; shift ;;
    -h|--help)  sed -n '2,21p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

log() { printf '%s\n' "$*" >&2; }
die() { log "deploy: $*"; exit 1; }

if [ ${#NAMES[@]} -eq 0 ]; then
  NAMES=(work); FILES=("${HOME}/.config/plane/proximal-mcp.env")
  if [ -r "${HOME}/.config/plane/harm-mcp.env" ]; then
    NAMES+=(personal); FILES+=("${HOME}/.config/plane/harm-mcp.env")
  else
    log "deploy: WARNING: ~/.config/plane/harm-mcp.env not readable; deploying work instance only"
  fi
fi
[ -n "$DEFAULT_NAME" ] || DEFAULT_NAME=${NAMES[0]}

REPO_DIR=$(cd "$(dirname "$0")/.." && pwd)
CONF_DIR="${HOME}/.config/plane-cli"
CONF="${CONF_DIR}/config.toml"
MARKER="# managed by plane-cli scripts/deploy.sh"

for i in "${!NAMES[@]}"; do
  case "${NAMES[$i]}" in
    *[!a-zA-Z0-9_-]*) die "instance name ${NAMES[$i]} must be [a-zA-Z0-9_-]" ;;
  esac
  [ -r "${FILES[$i]}" ] || die "env file not readable: ${FILES[$i]}"
done
case " ${NAMES[*]} " in
  *" $DEFAULT_NAME "*) ;;
  *) die "--default $DEFAULT_NAME does not match any --instance name" ;;
esac

# Extract values without exporting them into this shell's environment.
envval() { grep -E "^$2=" "$1" | head -1 | cut -d= -f2-; }

# 1. Build + install the binary.
log "deploy: building and installing to ${PREFIX}/bin/plane"
make -C "$REPO_DIR" install PREFIX="$PREFIX" >&2

# 2. config.toml — only overwrite what we generated, unless --force.
if [ -e "$CONF" ] && [ "$FORCE" -ne 1 ] && ! grep -qF "$MARKER" "$CONF"; then
  die "$CONF exists and was not generated by this script; pass --force to overwrite"
fi
mkdir -p "$CONF_DIR"
chmod 700 "$CONF_DIR"
umask 077

{
  printf '%s\n' "$MARKER"
  printf '# regenerate with: scripts/deploy.sh'
  for i in "${!NAMES[@]}"; do printf ' --instance %s=%s' "${NAMES[$i]}" "${FILES[$i]}"; done
  printf ' --default %s\n' "$DEFAULT_NAME"
  printf 'default_instance = "%s"\n' "$DEFAULT_NAME"
} > "$CONF.tmp"

for i in "${!NAMES[@]}"; do
  NAME=${NAMES[$i]} SRC=${FILES[$i]}
  BASE_URL=$(envval "$SRC" PLANE_BASE_URL)
  WORKSPACE=$(envval "$SRC" PLANE_WORKSPACE_SLUG)
  [ -n "$WORKSPACE" ] || WORKSPACE=$(envval "$SRC" PLANE_WORKSPACE)
  API_KEY=$(envval "$SRC" PLANE_API_KEY)
  [ -n "$BASE_URL" ]  || die "PLANE_BASE_URL missing in $SRC"
  [ -n "$WORKSPACE" ] || die "PLANE_WORKSPACE_SLUG/PLANE_WORKSPACE missing in $SRC"
  [ -n "$API_KEY" ]   || die "PLANE_API_KEY missing in $SRC"

  KEY_FILE="${CONF_DIR}/key-${NAME}"
  printf '%s\n' "$API_KEY" > "$KEY_FILE"
  chmod 600 "$KEY_FILE"
  log "deploy: wrote ${KEY_FILE} (0600)"

  cat >> "$CONF.tmp" <<EOF

[instance.${NAME}]
base_url     = "$BASE_URL"
workspace    = "$WORKSPACE"
api_key_file = "$KEY_FILE"
EOF
done

mv "$CONF.tmp" "$CONF"
chmod 600 "$CONF"
log "deploy: wrote ${CONF} (instances: ${NAMES[*]}; default: ${DEFAULT_NAME})"

# Remove the pre-instance key file this script used to manage.
if [ -e "${CONF_DIR}/key" ] && ! grep -qF "\"${CONF_DIR}/key\"" "$CONF"; then
  rm -f "${CONF_DIR}/key"
  log "deploy: removed stale ${CONF_DIR}/key"
fi

# 3. Verify each instance works from config alone (no PLANE_* env).
noenv() {
  env -u PLANE_API_KEY -u PLANE_API_KEY_FILE -u PLANE_BASE_URL -u PLANE_WORKSPACE \
      -u PLANE_PROJECT -u PLANE_INSTANCE -u PLANE_CONFIG "$@"
}
for NAME in "${NAMES[@]}"; do
  log "deploy: verifying instance ${NAME} with 'plane --instance ${NAME} me'"
  if OUT=$(noenv "${PREFIX}/bin/plane" --instance "$NAME" me 2>/dev/null); then
    log "deploy: OK — ${NAME}: authenticated as $(printf '%s' "$OUT" | jq -r '.data.display_name // .data.email')"
  else
    log "deploy: FAILED — 'plane --instance ${NAME} me' did not succeed; envelope follows"
    printf '%s\n' "$OUT" >&2
    exit 1
  fi
done
noenv "${PREFIX}/bin/plane" me >/dev/null || die "default-instance 'plane me' failed"
"${PREFIX}/bin/plane" version >/dev/null && log "deploy: $("${PREFIX}/bin/plane" version | jq -r '"version \(.data.version) (\(.data.commit)) targeting Plane \(.data.target_api)"')"
log "deploy: done"
