#!/usr/bin/env bash
# Local deployment for plane-cli: install the binary and generate
# ~/.config/plane-cli/ (config.toml + key file) from an existing
# KEY=value env file, so `plane` works standalone for any shell, agent,
# or systemd unit without sourcing anything.
#
# Usage: scripts/deploy.sh [--from-env FILE] [--prefix DIR] [--force]
#
#   --from-env FILE  env file containing PLANE_API_KEY, PLANE_BASE_URL and
#                    PLANE_WORKSPACE_SLUG (or PLANE_WORKSPACE).
#                    Default: ~/.config/plane/proximal-mcp.env if readable.
#   --prefix DIR     install prefix (binary goes to DIR/bin). Default ~/.local.
#   --force          overwrite a config.toml that this script did not generate.
#
# The API key is written to ~/.config/plane-cli/key (0600) and never printed.
set -euo pipefail

FROM_ENV="${HOME}/.config/plane/proximal-mcp.env"
PREFIX="${HOME}/.local"
FORCE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --from-env) FROM_ENV=$2; shift 2 ;;
    --prefix)   PREFIX=$2; shift 2 ;;
    --force)    FORCE=1; shift ;;
    -h|--help)  sed -n '2,16p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

log() { printf '%s\n' "$*" >&2; }
die() { log "deploy: $*"; exit 1; }

REPO_DIR=$(cd "$(dirname "$0")/.." && pwd)
CONF_DIR="${HOME}/.config/plane-cli"
CONF="${CONF_DIR}/config.toml"
KEY_FILE="${CONF_DIR}/key"
MARKER="# managed by plane-cli scripts/deploy.sh"

[ -r "$FROM_ENV" ] || die "env file not readable: $FROM_ENV (pass --from-env)"

# Extract values without exporting them into this shell's environment.
envval() { grep -E "^$1=" "$FROM_ENV" | head -1 | cut -d= -f2-; }
BASE_URL=$(envval PLANE_BASE_URL)
WORKSPACE=$(envval PLANE_WORKSPACE_SLUG)
[ -n "$WORKSPACE" ] || WORKSPACE=$(envval PLANE_WORKSPACE)
API_KEY=$(envval PLANE_API_KEY)
[ -n "$BASE_URL" ]  || die "PLANE_BASE_URL missing in $FROM_ENV"
[ -n "$WORKSPACE" ] || die "PLANE_WORKSPACE_SLUG/PLANE_WORKSPACE missing in $FROM_ENV"
[ -n "$API_KEY" ]   || die "PLANE_API_KEY missing in $FROM_ENV"

# 1. Build + install the binary.
log "deploy: building and installing to ${PREFIX}/bin/plane"
make -C "$REPO_DIR" install PREFIX="$PREFIX" >&2

# 2. Key file (0600, dir 0700). Refreshed on every deploy.
mkdir -p "$CONF_DIR"
chmod 700 "$CONF_DIR"
umask 077
printf '%s\n' "$API_KEY" > "$KEY_FILE"
chmod 600 "$KEY_FILE"
log "deploy: wrote ${KEY_FILE} (0600)"

# 3. config.toml — only overwrite what we generated, unless --force.
if [ -e "$CONF" ] && [ "$FORCE" -ne 1 ] && ! grep -qF "$MARKER" "$CONF"; then
  die "$CONF exists and was not generated by this script; pass --force to overwrite"
fi
cat > "$CONF" <<EOF
$MARKER
# regenerate with: scripts/deploy.sh --from-env $FROM_ENV
base_url     = "$BASE_URL"
workspace    = "$WORKSPACE"
api_key_file = "$KEY_FILE"
EOF
chmod 600 "$CONF"
log "deploy: wrote ${CONF}"

# 4. Verify the deployed binary works from config alone (no PLANE_* env).
log "deploy: verifying with 'plane me' (config-only environment)"
if OUT=$(env -u PLANE_API_KEY -u PLANE_API_KEY_FILE -u PLANE_BASE_URL \
             -u PLANE_WORKSPACE -u PLANE_PROJECT -u PLANE_CONFIG \
             "${PREFIX}/bin/plane" me 2>/dev/null); then
  log "deploy: OK — authenticated as $(printf '%s' "$OUT" | jq -r '.data.display_name // .data.email')"
else
  log "deploy: FAILED — 'plane me' did not succeed; envelope follows"
  printf '%s\n' "$OUT" >&2
  exit 1
fi
"${PREFIX}/bin/plane" version >/dev/null && log "deploy: $("${PREFIX}/bin/plane" version | jq -r '"version \(.data.version) (\(.data.commit)) targeting Plane \(.data.target_api)"')"
log "deploy: done"
